export const TESTIDS = {
  socketStatus: 'socket-status',
  mapCanvas: 'map-canvas',
  mapViewToggle: 'map-view-toggle',
  mapView2d: 'map-view-2d',
  mapView3d: 'map-view-3d',
  telemetryBattery: 'telemetry-battery',
  telemetryAltRlt: 'telemetry-alt-rlt',
  telemetryAltAgl: 'telemetry-alt-agl',
  telemetryAltAsl: 'telemetry-alt-asl',
  telemetryHSpeed: 'telemetry-hspeed',
  telemetryVSpeed: 'telemetry-vspeed',
  telemetryWind: 'telemetry-wind',
  telemetryHomeDistance: 'telemetry-home-distance',
  telemetryHeading: 'telemetry-heading',
  statusFlight: 'status-flight',
  videoPlayer: 'video-player',
  videoState: 'video-state',
  alertToast: 'alert-toast',
  // auth
  signinPage: 'signin-page',
  signinEmail: 'signin-email',
  signinOtpRequest: 'signin-otp-request',
  signinOtp: 'signin-otp',
  signinName: 'signin-name',
  signinSubmit: 'signin-submit',
  signinError: 'signin-error',
  userChip: 'user-chip',
  signOut: 'sign-out',
  navIncidents: 'nav-incidents',
  // incidents
  incidentsPage: 'incidents-page',
  incidentTitleInput: 'incident-title-input',
  incidentKindSelect: 'incident-kind-select',
  incidentCreateSubmit: 'incident-create-submit',
  incidentRow: (id: string) => `incident-row-${id}`,
  incidentOpen: (id: string) => `incident-open-${id}`,
  incidentJoinLink: (id: string) => `incident-join-link-${id}`,
  incidentCopyLink: (id: string) => `incident-copy-link-${id}`,
  incidentHistoryLink: (id: string) => `incident-history-link-${id}`,
  // join
  joinPage: 'join-page',
  joinTitle: 'join-title',
  joinConfirm: 'join-confirm',
  joinError: 'join-error',
  // incident dashboard
  incidentPage: 'incident-page',
  incidentTitle: 'incident-title',
  incidentStatus: 'incident-status',
  incidentDuration: 'incident-duration',
  copyJoinLink: 'copy-join-link',
  joinLinkValue: 'join-link-value',
  endIncident: 'end-incident',
  participantsList: 'participants-list',
  participantRow: (id: string) => `participant-row-${id}`,
  participantPresence: (id: string) => `participant-presence-${id}`,
  participantLocation: (id: string) => `participant-location-${id}`,
  participantVideo: (id: string) => `participant-video-${id}`,
  shareLocationToggle: 'share-location-toggle',
  shareVideoToggle: 'share-video-toggle',
  leaveIncident: 'leave-incident',
  chatPanel: 'chat-panel',
  chatMessages: 'chat-messages',
  chatInput: 'chat-input',
  chatSend: 'chat-send',
  chatMessage: (id: string) => `chat-message-${id}`,
  chatReply: (id: string) => `chat-reply-${id}`,
  chatReplyPreview: 'chat-reply-preview',
  markerLabel: 'marker-label',
  markerAdd: 'marker-add',
  markerUseMyLocation: 'marker-use-my-location',
  markersList: 'markers-list',
  markerRow: (id: string) => `marker-row-${id}`,
  commandTakeoff: 'command-takeoff',
  commandLand: 'command-land',
  freshness: (deviceId: string) => `freshness-${deviceId}`,
  // history
  historyPage: 'history-page',
  historyReadOnly: 'history-read-only',
  historyEvents: 'history-events',
  historyEvent: (id: string) => `history-event-${id}`,
  historyChat: 'history-chat',
  historyMarkers: 'history-markers',
} as const;

export const deviceRowTestId = (id: string) => `device-row-${id}`;
